function options = gen_save_options()
    key = {'foldername', 'filename', 'lineStyle', 'markerStyle', 'savefig', ...
        'title_font_size', 'sgtitle_font_size', 'label_font_size', 'legend_font_size', ...
        'labely_pos', 'savepdf'};
    value = {"", "", '--', 'none', true, ...
        12, 14, 12, 10, ...
        0, false};
    options = containers.Map(key, value);
end
